{
    config,
    pkgs,
    lib,
    ...
}:
{
    imports = [
        ./hyprland
        ./niri
        ./bemenu.nix
        ./coreServices.nix
        ./displayManager.nix
        ./environment.nix
        ./gtk.nix
        ./idleLock.nix
        ./keybinds.nix
        ./window.nix
        ./monitors.nix
    ];
}
