{
    osConfig,
    config,
    pkgs,
    lib,
    ...
}:
{
    imports = [
        ./bemenu.nix
        ./defaultApps.nix
        ./floorp.nix
        ./foot.nix
        ./gtkwave.nix
        ./helix.nix
        ./missioncenter.nix
        ./nemo.nix
        ./sublime.nix
        ./vscodium.nix
        ./zsh.nix
    ];
}
