{
    osConfig,
    config,
    pkgs,
    lib,
    ...
}:
{
    imports = [
        ./appLauncher.nix
        ./audio.nix
        ./bar.nix
        ./brightness.nix
        ./calendar.nix
        ./colorSchemes.nix
        ./controlCenter.nix
        ./desktopWidgets.nix
        ./dock.nix
        ./general.nix
        ./hooks.nix
        ./idle.nix
        ./location.nix
        ./network.nix
        ./nightLight.nix
        ./noctaliaPerformance.nix
        ./notifications.nix
        ./osd.nix
        ./plugins
        ./sessionMenu.nix
        ./systemMonitor.nix
        ./templates.nix
        ./ui.nix
        ./wallpaper.nix
    ];
}
